# Generated by Django 5.0.4 on 2024-05-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxidetails',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
